Exception on /index [GET]
Traceback (most recent call last):
  File "/home/deeplearning/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/deeplearning/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/deeplearning/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/deeplearning/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/deeplearning/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/deeplearning/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/deeplearning/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/deeplearning/microblog/app/routes.py", line 19, in index
    page = requests.args.get('page', 1, type=int)
NameError: name 'requests' is not defined
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
